# Project information

site_name: Permission Boundaries How to Truly Delegate Permissions on AWS 
site_short_name: Permission Boundaries
site_description: 'Permission boundaries is probably one of the most important new IAM features that has launched in a while. This feature addresses a longstanding customer issue, namely, how do I delegate administration to my users. If you have system administrators that need to be able to create IAM roles and users, developers that need to be able to create roles for Lambda functions, or any similar scenario, then you need permission boundaries.'
site_author: 'aws-security-workshops@amazon.com'
site_url: 'https://permissions-boundaries.awssecworkshops.com/'

# Repository
repo_name: 'aws-samples/aws-permission-boundaries-builder-session'
repo_url: 'https://github.com/aws-samples/aws-permissions-boundaries-builder-session'

# Copyright
copyright: '<a href="https://aws.amazon.com/privacy/" target="_blank">Privacy</a> | <a href="https://aws.amazon.com/terms/" target="_blank">Site terms</a> | &copy; 2020, Amazon Web Services, Inc. or its affiliates. All rights reserved.'

# Configuration
theme:
  name: 'material'
  logo: 'assets/images/aws_smile_logo.png'
  favicon: 'assets/images/aws-favicon.ico'

# Customization
extra_css:
  - 'stylesheets/custom.css'
extra:
  social:
    - icon: fontawesome/solid/home
      link: https://awssecworkshops.com
    - icon: fontawesome/solid/shield-alt
      link: https://aws.amazon.com/security/
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/awssecurityinfo?lang=en
    - icon: fontawesome/solid/rss-square
      link: https://aws.amazon.com/blogs/security/

# Extensions
markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.details

# Navigation
nav:
  - 'Overview': 'index.md'
  - 'Module 1: Environment Build': '01-build.md'
  - 'Module 2: Verify Stage': '02-verify.md'
  - Contributing: 'contribute.md'
  - License: 'license.md'
